-- RE/MAX Platinum — seed data (Sections 3.4).
-- Idempotent: safe to re-run. Inserts the 4 launch cities + singleton config rows.

INSERT INTO locations (slug, name, state, latitude, longitude, meta_title, meta_description, hero_headline, hero_subheadline, faq_json, is_active)
VALUES ('brighton-mi', 'Brighton, Michigan', 'MI', 42.5295, -83.7799, 'Brighton MI Home Values & Free Home Valuation | RE/MAX Platinum', 'Find out what your Brighton, MI home is worth. Free home valuation from RE/MAX Platinum — local experts. See current market stats and recent sales.', 'What Is My Home Worth in Brighton, MI?', 'Get a free, instant home valuation based on recent Brighton sales — then connect with a local RE/MAX Platinum expert to maximize your sale price.', '[{"question": "How much is my home worth in Brighton, MI?", "answer": "Home values in Brighton, MI vary by neighborhood, condition, and current market demand. Enter your address above for a free instant estimate based on recent Brighton sales, then connect with a local RE/MAX Platinum expert for a precise valuation."}, {"question": "How long does it take to sell a home in Brighton?", "answer": "Average time-to-sell in Brighton depends on pricing and market conditions. Our local agents price strategically to sell quickly while maximizing your return."}, {"question": "What percentage of asking price do homes sell for in Brighton?", "answer": "Well-priced Brighton homes routinely sell at or above asking. We track current sale-to-list ratios so your home is priced to compete."}, {"question": "Do I need to make repairs before selling?", "answer": "Not always. RE/MAX Platinum advises on the highest-ROI improvements \u2014 and which to skip \u2014 so you don''t overspend before listing. Many homes sell as-is."}, {"question": "How do I get started?", "answer": "Enter your address in the valuation tool above to get your free estimate. A local RE/MAX Platinum expert will follow up to review your personalized market report."}]', true)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, state = EXCLUDED.state, latitude = EXCLUDED.latitude, longitude = EXCLUDED.longitude,
  meta_title = EXCLUDED.meta_title, meta_description = EXCLUDED.meta_description,
  hero_headline = EXCLUDED.hero_headline, hero_subheadline = EXCLUDED.hero_subheadline,
  faq_json = EXCLUDED.faq_json, is_active = true, updated_at = now();

INSERT INTO locations (slug, name, state, latitude, longitude, meta_title, meta_description, hero_headline, hero_subheadline, faq_json, is_active)
VALUES ('ann-arbor-mi', 'Ann Arbor, Michigan', 'MI', 42.2808, -83.743, 'Ann Arbor MI Home Values & Free Home Valuation | RE/MAX Platinum', 'Find out what your Ann Arbor, MI home is worth. Free home valuation from RE/MAX Platinum — local experts. See current market stats and recent sales.', 'What Is My Home Worth in Ann Arbor, MI?', 'Get a free, instant home valuation based on recent Ann Arbor sales — then connect with a local RE/MAX Platinum expert to maximize your sale price.', '[{"question": "How much is my home worth in Ann Arbor, MI?", "answer": "Home values in Ann Arbor, MI vary by neighborhood, condition, and current market demand. Enter your address above for a free instant estimate based on recent Ann Arbor sales, then connect with a local RE/MAX Platinum expert for a precise valuation."}, {"question": "How long does it take to sell a home in Ann Arbor?", "answer": "Average time-to-sell in Ann Arbor depends on pricing and market conditions. Our local agents price strategically to sell quickly while maximizing your return."}, {"question": "What percentage of asking price do homes sell for in Ann Arbor?", "answer": "Well-priced Ann Arbor homes routinely sell at or above asking. We track current sale-to-list ratios so your home is priced to compete."}, {"question": "Do I need to make repairs before selling?", "answer": "Not always. RE/MAX Platinum advises on the highest-ROI improvements \u2014 and which to skip \u2014 so you don''t overspend before listing. Many homes sell as-is."}, {"question": "How do I get started?", "answer": "Enter your address in the valuation tool above to get your free estimate. A local RE/MAX Platinum expert will follow up to review your personalized market report."}]', true)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, state = EXCLUDED.state, latitude = EXCLUDED.latitude, longitude = EXCLUDED.longitude,
  meta_title = EXCLUDED.meta_title, meta_description = EXCLUDED.meta_description,
  hero_headline = EXCLUDED.hero_headline, hero_subheadline = EXCLUDED.hero_subheadline,
  faq_json = EXCLUDED.faq_json, is_active = true, updated_at = now();

INSERT INTO locations (slug, name, state, latitude, longitude, meta_title, meta_description, hero_headline, hero_subheadline, faq_json, is_active)
VALUES ('fenton-mi', 'Fenton, Michigan', 'MI', 42.7959, -83.7085, 'Fenton MI Home Values & Free Home Valuation | RE/MAX Platinum', 'Find out what your Fenton, MI home is worth. Free home valuation from RE/MAX Platinum — local experts. See current market stats and recent sales.', 'What Is My Home Worth in Fenton, MI?', 'Get a free, instant home valuation based on recent Fenton sales — then connect with a local RE/MAX Platinum expert to maximize your sale price.', '[{"question": "How much is my home worth in Fenton, MI?", "answer": "Home values in Fenton, MI vary by neighborhood, condition, and current market demand. Enter your address above for a free instant estimate based on recent Fenton sales, then connect with a local RE/MAX Platinum expert for a precise valuation."}, {"question": "How long does it take to sell a home in Fenton?", "answer": "Average time-to-sell in Fenton depends on pricing and market conditions. Our local agents price strategically to sell quickly while maximizing your return."}, {"question": "What percentage of asking price do homes sell for in Fenton?", "answer": "Well-priced Fenton homes routinely sell at or above asking. We track current sale-to-list ratios so your home is priced to compete."}, {"question": "Do I need to make repairs before selling?", "answer": "Not always. RE/MAX Platinum advises on the highest-ROI improvements \u2014 and which to skip \u2014 so you don''t overspend before listing. Many homes sell as-is."}, {"question": "How do I get started?", "answer": "Enter your address in the valuation tool above to get your free estimate. A local RE/MAX Platinum expert will follow up to review your personalized market report."}]', true)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, state = EXCLUDED.state, latitude = EXCLUDED.latitude, longitude = EXCLUDED.longitude,
  meta_title = EXCLUDED.meta_title, meta_description = EXCLUDED.meta_description,
  hero_headline = EXCLUDED.hero_headline, hero_subheadline = EXCLUDED.hero_subheadline,
  faq_json = EXCLUDED.faq_json, is_active = true, updated_at = now();

INSERT INTO locations (slug, name, state, latitude, longitude, meta_title, meta_description, hero_headline, hero_subheadline, faq_json, is_active)
VALUES ('grand-blanc-mi', 'Grand Blanc, Michigan', 'MI', 42.9267, -83.6305, 'Grand Blanc MI Home Values & Free Home Valuation | RE/MAX Platinum', 'Find out what your Grand Blanc, MI home is worth. Free home valuation from RE/MAX Platinum — local experts. See current market stats and recent sales.', 'What Is My Home Worth in Grand Blanc, MI?', 'Get a free, instant home valuation based on recent Grand Blanc sales — then connect with a local RE/MAX Platinum expert to maximize your sale price.', '[{"question": "How much is my home worth in Grand Blanc, MI?", "answer": "Home values in Grand Blanc, MI vary by neighborhood, condition, and current market demand. Enter your address above for a free instant estimate based on recent Grand Blanc sales, then connect with a local RE/MAX Platinum expert for a precise valuation."}, {"question": "How long does it take to sell a home in Grand Blanc?", "answer": "Average time-to-sell in Grand Blanc depends on pricing and market conditions. Our local agents price strategically to sell quickly while maximizing your return."}, {"question": "What percentage of asking price do homes sell for in Grand Blanc?", "answer": "Well-priced Grand Blanc homes routinely sell at or above asking. We track current sale-to-list ratios so your home is priced to compete."}, {"question": "Do I need to make repairs before selling?", "answer": "Not always. RE/MAX Platinum advises on the highest-ROI improvements \u2014 and which to skip \u2014 so you don''t overspend before listing. Many homes sell as-is."}, {"question": "How do I get started?", "answer": "Enter your address in the valuation tool above to get your free estimate. A local RE/MAX Platinum expert will follow up to review your personalized market report."}]', true)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, state = EXCLUDED.state, latitude = EXCLUDED.latitude, longitude = EXCLUDED.longitude,
  meta_title = EXCLUDED.meta_title, meta_description = EXCLUDED.meta_description,
  hero_headline = EXCLUDED.hero_headline, hero_subheadline = EXCLUDED.hero_subheadline,
  faq_json = EXCLUDED.faq_json, is_active = true, updated_at = now();

-- Singleton config rows (only if absent)
INSERT INTO notification_settings (offer_window_start_hour, offer_window_end_hour, proximity_radius_miles, queue_pointer)
SELECT 7, 20, 20, 0 WHERE NOT EXISTS (SELECT 1 FROM notification_settings);

INSERT INTO home_page_metrics (total_homes_sold, avg_days_to_sell, avg_sale_price)
SELECT NULL, NULL, NULL WHERE NOT EXISTS (SELECT 1 FROM home_page_metrics);
