-- Additional launch-city location records (homepage "Explore Your Market" tiles).
--
-- The homepage tiles and the /sell/[slug] community pages are both generated
-- from active `locations` rows (getCityTiles / getActiveLocations), so growing
-- from 4 tiles to 12 is purely data: this adds 8 mailing cities near the
-- Brighton and Ann Arbor offices where RE/MAX Platinum carries active listings.
-- Fenton and Grand Blanc stay from the original seed.
--
-- SEO/FAQ copy matches the scripts/seed.ts `buildSeo` template exactly; it is
-- admin-editable without redeploy, so these are sensible starting stubs. Stats
-- and tile photos fill in at render time from market_stats / IDX office data.
--
-- ON CONFLICT (slug) DO NOTHING: idempotent and NON-clobbering — if a slug
-- already exists (admin-added, or a re-run), the existing row and any admin
-- edits are left untouched. Hand-authored (lessons-learned §1).

INSERT INTO locations (slug, name, state, latitude, longitude, meta_title, meta_description, hero_headline, hero_subheadline, faq_json, is_active)
VALUES ('howell-mi', 'Howell, Michigan', 'MI', 42.6073, -83.9294, 'Howell MI Home Values & Free Home Valuation | RE/MAX Platinum', 'Find out what your Howell, MI home is worth. Free home valuation from RE/MAX Platinum — local experts. See current market stats and recent sales.', 'What Is My Home Worth in Howell, MI?', 'Get a free, instant home valuation based on recent Howell sales — then connect with a local RE/MAX Platinum expert to maximize your sale price.', '[{"question":"How much is my home worth in Howell, MI?","answer":"Home values in Howell, MI vary by neighborhood, condition, and current market demand. Enter your address above for a free instant estimate based on recent Howell sales, then connect with a local RE/MAX Platinum expert for a precise valuation."},{"question":"How long does it take to sell a home in Howell?","answer":"Average time-to-sell in Howell depends on pricing and market conditions. Our local agents price strategically to sell quickly while maximizing your return."},{"question":"What percentage of asking price do homes sell for in Howell?","answer":"Well-priced Howell homes routinely sell at or above asking. We track current sale-to-list ratios so your home is priced to compete."},{"question":"Do I need to make repairs before selling?","answer":"Not always. RE/MAX Platinum advises on the highest-ROI improvements — and which to skip — so you don''t overspend before listing. Many homes sell as-is."},{"question":"How do I get started?","answer":"Enter your address in the valuation tool above to get your free estimate. A local RE/MAX Platinum expert will follow up to review your personalized market report."}]', true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO locations (slug, name, state, latitude, longitude, meta_title, meta_description, hero_headline, hero_subheadline, faq_json, is_active)
VALUES ('hartland-mi', 'Hartland, Michigan', 'MI', 42.6531, -83.7477, 'Hartland MI Home Values & Free Home Valuation | RE/MAX Platinum', 'Find out what your Hartland, MI home is worth. Free home valuation from RE/MAX Platinum — local experts. See current market stats and recent sales.', 'What Is My Home Worth in Hartland, MI?', 'Get a free, instant home valuation based on recent Hartland sales — then connect with a local RE/MAX Platinum expert to maximize your sale price.', '[{"question":"How much is my home worth in Hartland, MI?","answer":"Home values in Hartland, MI vary by neighborhood, condition, and current market demand. Enter your address above for a free instant estimate based on recent Hartland sales, then connect with a local RE/MAX Platinum expert for a precise valuation."},{"question":"How long does it take to sell a home in Hartland?","answer":"Average time-to-sell in Hartland depends on pricing and market conditions. Our local agents price strategically to sell quickly while maximizing your return."},{"question":"What percentage of asking price do homes sell for in Hartland?","answer":"Well-priced Hartland homes routinely sell at or above asking. We track current sale-to-list ratios so your home is priced to compete."},{"question":"Do I need to make repairs before selling?","answer":"Not always. RE/MAX Platinum advises on the highest-ROI improvements — and which to skip — so you don''t overspend before listing. Many homes sell as-is."},{"question":"How do I get started?","answer":"Enter your address in the valuation tool above to get your free estimate. A local RE/MAX Platinum expert will follow up to review your personalized market report."}]', true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO locations (slug, name, state, latitude, longitude, meta_title, meta_description, hero_headline, hero_subheadline, faq_json, is_active)
VALUES ('pinckney-mi', 'Pinckney, Michigan', 'MI', 42.457, -83.9477, 'Pinckney MI Home Values & Free Home Valuation | RE/MAX Platinum', 'Find out what your Pinckney, MI home is worth. Free home valuation from RE/MAX Platinum — local experts. See current market stats and recent sales.', 'What Is My Home Worth in Pinckney, MI?', 'Get a free, instant home valuation based on recent Pinckney sales — then connect with a local RE/MAX Platinum expert to maximize your sale price.', '[{"question":"How much is my home worth in Pinckney, MI?","answer":"Home values in Pinckney, MI vary by neighborhood, condition, and current market demand. Enter your address above for a free instant estimate based on recent Pinckney sales, then connect with a local RE/MAX Platinum expert for a precise valuation."},{"question":"How long does it take to sell a home in Pinckney?","answer":"Average time-to-sell in Pinckney depends on pricing and market conditions. Our local agents price strategically to sell quickly while maximizing your return."},{"question":"What percentage of asking price do homes sell for in Pinckney?","answer":"Well-priced Pinckney homes routinely sell at or above asking. We track current sale-to-list ratios so your home is priced to compete."},{"question":"Do I need to make repairs before selling?","answer":"Not always. RE/MAX Platinum advises on the highest-ROI improvements — and which to skip — so you don''t overspend before listing. Many homes sell as-is."},{"question":"How do I get started?","answer":"Enter your address in the valuation tool above to get your free estimate. A local RE/MAX Platinum expert will follow up to review your personalized market report."}]', true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO locations (slug, name, state, latitude, longitude, meta_title, meta_description, hero_headline, hero_subheadline, faq_json, is_active)
VALUES ('south-lyon-mi', 'South Lyon, Michigan', 'MI', 42.4606, -83.6516, 'South Lyon MI Home Values & Free Home Valuation | RE/MAX Platinum', 'Find out what your South Lyon, MI home is worth. Free home valuation from RE/MAX Platinum — local experts. See current market stats and recent sales.', 'What Is My Home Worth in South Lyon, MI?', 'Get a free, instant home valuation based on recent South Lyon sales — then connect with a local RE/MAX Platinum expert to maximize your sale price.', '[{"question":"How much is my home worth in South Lyon, MI?","answer":"Home values in South Lyon, MI vary by neighborhood, condition, and current market demand. Enter your address above for a free instant estimate based on recent South Lyon sales, then connect with a local RE/MAX Platinum expert for a precise valuation."},{"question":"How long does it take to sell a home in South Lyon?","answer":"Average time-to-sell in South Lyon depends on pricing and market conditions. Our local agents price strategically to sell quickly while maximizing your return."},{"question":"What percentage of asking price do homes sell for in South Lyon?","answer":"Well-priced South Lyon homes routinely sell at or above asking. We track current sale-to-list ratios so your home is priced to compete."},{"question":"Do I need to make repairs before selling?","answer":"Not always. RE/MAX Platinum advises on the highest-ROI improvements — and which to skip — so you don''t overspend before listing. Many homes sell as-is."},{"question":"How do I get started?","answer":"Enter your address in the valuation tool above to get your free estimate. A local RE/MAX Platinum expert will follow up to review your personalized market report."}]', true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO locations (slug, name, state, latitude, longitude, meta_title, meta_description, hero_headline, hero_subheadline, faq_json, is_active)
VALUES ('saline-mi', 'Saline, Michigan', 'MI', 42.1667, -83.7813, 'Saline MI Home Values & Free Home Valuation | RE/MAX Platinum', 'Find out what your Saline, MI home is worth. Free home valuation from RE/MAX Platinum — local experts. See current market stats and recent sales.', 'What Is My Home Worth in Saline, MI?', 'Get a free, instant home valuation based on recent Saline sales — then connect with a local RE/MAX Platinum expert to maximize your sale price.', '[{"question":"How much is my home worth in Saline, MI?","answer":"Home values in Saline, MI vary by neighborhood, condition, and current market demand. Enter your address above for a free instant estimate based on recent Saline sales, then connect with a local RE/MAX Platinum expert for a precise valuation."},{"question":"How long does it take to sell a home in Saline?","answer":"Average time-to-sell in Saline depends on pricing and market conditions. Our local agents price strategically to sell quickly while maximizing your return."},{"question":"What percentage of asking price do homes sell for in Saline?","answer":"Well-priced Saline homes routinely sell at or above asking. We track current sale-to-list ratios so your home is priced to compete."},{"question":"Do I need to make repairs before selling?","answer":"Not always. RE/MAX Platinum advises on the highest-ROI improvements — and which to skip — so you don''t overspend before listing. Many homes sell as-is."},{"question":"How do I get started?","answer":"Enter your address in the valuation tool above to get your free estimate. A local RE/MAX Platinum expert will follow up to review your personalized market report."}]', true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO locations (slug, name, state, latitude, longitude, meta_title, meta_description, hero_headline, hero_subheadline, faq_json, is_active)
VALUES ('dexter-mi', 'Dexter, Michigan', 'MI', 42.3389, -83.8894, 'Dexter MI Home Values & Free Home Valuation | RE/MAX Platinum', 'Find out what your Dexter, MI home is worth. Free home valuation from RE/MAX Platinum — local experts. See current market stats and recent sales.', 'What Is My Home Worth in Dexter, MI?', 'Get a free, instant home valuation based on recent Dexter sales — then connect with a local RE/MAX Platinum expert to maximize your sale price.', '[{"question":"How much is my home worth in Dexter, MI?","answer":"Home values in Dexter, MI vary by neighborhood, condition, and current market demand. Enter your address above for a free instant estimate based on recent Dexter sales, then connect with a local RE/MAX Platinum expert for a precise valuation."},{"question":"How long does it take to sell a home in Dexter?","answer":"Average time-to-sell in Dexter depends on pricing and market conditions. Our local agents price strategically to sell quickly while maximizing your return."},{"question":"What percentage of asking price do homes sell for in Dexter?","answer":"Well-priced Dexter homes routinely sell at or above asking. We track current sale-to-list ratios so your home is priced to compete."},{"question":"Do I need to make repairs before selling?","answer":"Not always. RE/MAX Platinum advises on the highest-ROI improvements — and which to skip — so you don''t overspend before listing. Many homes sell as-is."},{"question":"How do I get started?","answer":"Enter your address in the valuation tool above to get your free estimate. A local RE/MAX Platinum expert will follow up to review your personalized market report."}]', true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO locations (slug, name, state, latitude, longitude, meta_title, meta_description, hero_headline, hero_subheadline, faq_json, is_active)
VALUES ('chelsea-mi', 'Chelsea, Michigan', 'MI', 42.3184, -84.0197, 'Chelsea MI Home Values & Free Home Valuation | RE/MAX Platinum', 'Find out what your Chelsea, MI home is worth. Free home valuation from RE/MAX Platinum — local experts. See current market stats and recent sales.', 'What Is My Home Worth in Chelsea, MI?', 'Get a free, instant home valuation based on recent Chelsea sales — then connect with a local RE/MAX Platinum expert to maximize your sale price.', '[{"question":"How much is my home worth in Chelsea, MI?","answer":"Home values in Chelsea, MI vary by neighborhood, condition, and current market demand. Enter your address above for a free instant estimate based on recent Chelsea sales, then connect with a local RE/MAX Platinum expert for a precise valuation."},{"question":"How long does it take to sell a home in Chelsea?","answer":"Average time-to-sell in Chelsea depends on pricing and market conditions. Our local agents price strategically to sell quickly while maximizing your return."},{"question":"What percentage of asking price do homes sell for in Chelsea?","answer":"Well-priced Chelsea homes routinely sell at or above asking. We track current sale-to-list ratios so your home is priced to compete."},{"question":"Do I need to make repairs before selling?","answer":"Not always. RE/MAX Platinum advises on the highest-ROI improvements — and which to skip — so you don''t overspend before listing. Many homes sell as-is."},{"question":"How do I get started?","answer":"Enter your address in the valuation tool above to get your free estimate. A local RE/MAX Platinum expert will follow up to review your personalized market report."}]', true)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO locations (slug, name, state, latitude, longitude, meta_title, meta_description, hero_headline, hero_subheadline, faq_json, is_active)
VALUES ('whitmore-lake-mi', 'Whitmore Lake, Michigan', 'MI', 42.4319, -83.75, 'Whitmore Lake MI Home Values & Free Home Valuation | RE/MAX Platinum', 'Find out what your Whitmore Lake, MI home is worth. Free home valuation from RE/MAX Platinum — local experts. See current market stats and recent sales.', 'What Is My Home Worth in Whitmore Lake, MI?', 'Get a free, instant home valuation based on recent Whitmore Lake sales — then connect with a local RE/MAX Platinum expert to maximize your sale price.', '[{"question":"How much is my home worth in Whitmore Lake, MI?","answer":"Home values in Whitmore Lake, MI vary by neighborhood, condition, and current market demand. Enter your address above for a free instant estimate based on recent Whitmore Lake sales, then connect with a local RE/MAX Platinum expert for a precise valuation."},{"question":"How long does it take to sell a home in Whitmore Lake?","answer":"Average time-to-sell in Whitmore Lake depends on pricing and market conditions. Our local agents price strategically to sell quickly while maximizing your return."},{"question":"What percentage of asking price do homes sell for in Whitmore Lake?","answer":"Well-priced Whitmore Lake homes routinely sell at or above asking. We track current sale-to-list ratios so your home is priced to compete."},{"question":"Do I need to make repairs before selling?","answer":"Not always. RE/MAX Platinum advises on the highest-ROI improvements — and which to skip — so you don''t overspend before listing. Many homes sell as-is."},{"question":"How do I get started?","answer":"Enter your address in the valuation tool above to get your free estimate. A local RE/MAX Platinum expert will follow up to review your personalized market report."}]', true)
ON CONFLICT (slug) DO NOTHING;
