import type { Metadata } from 'next';
import LegalPage, { LegalSection, LegalSub, LegalList } from '@/components/LegalPage';

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description:
    "RE/MAX Platinum's privacy policy: how we collect, use, and protect your information when you request a home valuation.",
  robots: { index: false, follow: true },
};

export default function PrivacyPage() {
  return (
    <LegalPage title="Privacy Policy" lastUpdated="February 19, 2026">
      <LegalSection heading="Introduction">
        <p>
          RE/MAX Platinum (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;) is committed to protecting your
          privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information
          when you visit our website and use our home valuation tools and services. By using our website, you
          consent to the data practices described in this policy.
        </p>
      </LegalSection>

      <LegalSection heading="Information We Collect">
        <LegalSub>Personal Information You Provide</LegalSub>
        <p>
          When you request a home valuation, download our Seller&apos;s Guide, or contact us through our
          website, we collect personal information that you voluntarily provide, including:
        </p>
        <LegalList
          items={[
            'Full name (first and last name)',
            'Email address',
            'Phone number',
            'Property address',
            'Selling timeframe preferences',
            'Any additional information you choose to provide in messages or forms',
          ]}
        />
        <LegalSub>Automatically Collected Information</LegalSub>
        <p>
          When you visit our website, we automatically collect certain information about your device and
          browsing behavior, including:
        </p>
        <LegalList
          items={[
            'IP address and geographic location',
            'Browser type and version',
            'Operating system',
            'Pages visited and time spent on pages',
            'Referring website addresses',
            'Date and time of visits',
            'Advertising click identifiers and campaign attribution parameters, such as Google Click ID and UTM parameters, when present',
          ]}
        />
        <LegalSub>Property Valuation Data</LegalSub>
        <p>
          When you use our home valuation tool, we collect and process property information including the
          address you provide and estimated property values generated by third-party valuation services. This
          information is used solely to provide you with accurate home valuations and connect you with our real
          estate professionals.
        </p>
      </LegalSection>

      <LegalSection heading="How We Use Your Information">
        <p>We use the information we collect for the following purposes:</p>
        <LegalList
          items={[
            <><strong>Provide Services:</strong> To deliver home valuations, respond to your inquiries, and provide real estate services</>,
            <><strong>Communication:</strong> To contact you about your property, market updates, and relevant real estate opportunities</>,
            <><strong>CRM Integration:</strong> To add your information to our customer relationship management system for follow-up and service delivery</>,
            <><strong>Improve Our Services:</strong> To analyze website usage and improve our tools, content, and user experience</>,
            <><strong>Advertising Measurement:</strong> To measure which ads and campaigns generate completed lead forms, guide downloads, and appointment requests</>,
            <><strong>Marketing:</strong> To send you information about our services, market insights, and promotional offers (you may opt out at any time)</>,
            <><strong>Legal Compliance:</strong> To comply with applicable laws, regulations, and legal processes</>,
          ]}
        />
      </LegalSection>

      <LegalSection heading="How We Share Your Information">
        <p>We may share your information in the following circumstances:</p>
        <LegalList
          items={[
            <><strong>RE/MAX Platinum Agents:</strong> Your information is shared with our licensed real estate agents who will contact you to provide requested services</>,
            <><strong>Service Providers:</strong> We share information with third-party service providers who assist us in operating our website and delivering services, including RentCast (property valuation API), Google Maps (address autocomplete and location services), Google Ads and analytics providers for conversion measurement and campaign attribution, and web hosting providers</>,
            <><strong>Legal Requirements:</strong> We may disclose information when required by law, court order, or government request</>,
            <><strong>Business Transfers:</strong> In the event of a merger, acquisition, or sale of assets, your information may be transferred to the acquiring entity</>,
          ]}
        />
        <p>
          <strong>We do not sell your personal information to third parties.</strong>
        </p>
      </LegalSection>

      <LegalSection heading="SMS / Text Messaging">
        <p>
          We send text messages to our affiliated real estate agents for lead notifications, lead-detail
          delivery, and status-update reminders. Agents opt in by activating notifications in the agent
          portal and can opt out at any time by replying STOP (reply HELP for help).
        </p>
        <p>Message frequency varies; message and data rates may apply.</p>
        <p>
          <strong>
            Mobile phone numbers and SMS opt-in consent are not shared with or sold to any third parties or
            affiliates for their own marketing or promotional purposes.
          </strong>{' '}
          Text messaging originator opt-in data and consent will not be shared with any third parties.
        </p>
      </LegalSection>

      <LegalSection heading="Cookies and Tracking Technologies">
        <p>
          Our website uses cookies and similar tracking technologies (including Google Tag Manager, Google
          Analytics, and Microsoft Clarity) to enhance your browsing experience and analyze website traffic.
          Cookies are small text files stored on your device that help us remember your preferences and
          understand how you use our site.
        </p>
        <p>
          We may use Google Ads conversion tracking and enhanced conversions to understand whether our ads
          result in completed lead forms or appointment requests. When you voluntarily submit a form, limited
          contact information such as your email address and phone number may be securely hashed and processed
          through Google tag technology for conversion measurement.
        </p>
        <p>
          You can control cookies through your browser settings. However, disabling cookies may limit your
          ability to use certain features of our website.
        </p>
      </LegalSection>

      <LegalSection heading="Data Security">
        <p>
          We implement reasonable security measures to protect your personal information from unauthorized
          access, disclosure, alteration, and destruction. However, no method of transmission over the internet
          or electronic storage is 100% secure. While we strive to protect your information, we cannot guarantee
          absolute security.
        </p>
      </LegalSection>

      <LegalSection heading="Your Privacy Rights">
        <p>
          Depending on your location, you may have certain rights regarding your personal information,
          including:
        </p>
        <LegalList
          items={[
            <><strong>Access:</strong> Request access to the personal information we hold about you</>,
            <><strong>Correction:</strong> Request correction of inaccurate or incomplete information</>,
            <><strong>Deletion:</strong> Request deletion of your personal information (subject to legal obligations)</>,
            <><strong>Opt-Out:</strong> Unsubscribe from marketing communications at any time</>,
            <><strong>Data Portability:</strong> Request a copy of your information in a portable format</>,
          ]}
        />
        <p>To exercise any of these rights, please contact us using the information provided below.</p>
      </LegalSection>

      <LegalSection heading="Children's Privacy">
        <p>
          Our website and services are not intended for individuals under the age of 18. We do not knowingly
          collect personal information from children. If you believe we have inadvertently collected information
          from a child, please contact us immediately so we can delete it.
        </p>
      </LegalSection>

      <LegalSection heading="Changes to This Privacy Policy">
        <p>
          We may update this Privacy Policy from time to time to reflect changes in our practices or legal
          requirements. We will post the updated policy on this page with a new &quot;Last Updated&quot; date. We
          encourage you to review this policy periodically.
        </p>
      </LegalSection>

      <LegalSection heading="Contact Us">
        <p>
          If you have questions or concerns about this Privacy Policy or our data practices, please contact us:
        </p>
        <div className="rounded-card border border-line bg-cream p-5">
          <p className="font-semibold text-charcoal">RE/MAX Platinum</p>
          <p className="text-mute">6870 Grand River Ave</p>
          <p className="text-mute">Brighton, MI 48114</p>
          <p className="mt-2 text-mute">
            <strong>Phone:</strong>{' '}
            <a href="tel:810-227-4600" className="text-platinum-blue hover:underline">
              810-227-4600
            </a>
          </p>
        </div>
      </LegalSection>
    </LegalPage>
  );
}
