'use client';

import * as React from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Toggle } from '@/components/ui';

/**
 * Agent-controlled lead routing toggle (Section 16.4). Lives in the portal
 * sidebar, styled per the Charcoal Light panel pattern. Optimistic update,
 * then router.refresh() so the header pill (server-rendered) stays in sync.
 *
 * Turning this ON is how an agent accepts the 30% referral back to RE/MAX
 * Platinum, so the terms are stated HERE, next to the switch — an agent should
 * never have to remember a line from an onboarding email to know what they are
 * agreeing to. The API records the acceptance (agents.availabilityOptedInAt).
 */
export default function AvailabilityToggle({ initial }: { initial: boolean }) {
  const router = useRouter();
  const [available, setAvailable] = React.useState(initial);
  const [busy, setBusy] = React.useState(false);

  async function toggle(next: boolean) {
    setAvailable(next);
    setBusy(true);
    try {
      const res = await fetch('/api/agent/availability', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ available: next }),
      });
      if (!res.ok) throw new Error('failed');
      router.refresh();
    } catch {
      setAvailable(!next); // revert on failure
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="rounded-card bg-charcoal-light p-4">
      <div className="flex items-center justify-between">
        <span className="text-xs font-bold uppercase tracking-wide text-mute-lighter">
          Lead routing
        </span>
        <Toggle checked={available} onChange={toggle} disabled={busy} label="Toggle lead routing" />
      </div>
      <p className="mt-2 text-xs text-mute-lighter">
        {available
          ? "You're receiving new leads."
          : 'New leads are paused. You can still see and work your current leads.'}
      </p>
      <p className="mt-2 text-xs text-mute-lighter">
        Activating yourself turns on text-message lead notifications to your mobile number on
        file. Message &amp; data rates may apply; reply STOP to any text to opt out.
      </p>
      {/* The commercial term. Deliberately the most prominent text in this
          panel — it is what turning the switch on commits the agent to.
          The link matters: this switch IS the acceptance, so the full terms
          (how much, when, the two-deal window, desk fees) have to be reachable
          from the point of agreement rather than only from a page the agent may
          never have opened. */}
      <div className="mt-3 border-t border-white/10 pt-3">
        <p className="text-xs font-bold uppercase tracking-wide text-white">Referral terms</p>
        <p className="mt-1 text-xs leading-relaxed text-white/80">
          Each lead generated by the system is a{' '}
          <strong className="font-bold text-white">30% referral back to RE/MAX Platinum</strong>. By
          turning on your availability you are agreeing to this referral.
        </p>
        <Link
          href="/agent/help#availability"
          className="mt-1.5 inline-block text-xs font-semibold text-white underline underline-offset-2 hover:text-mute-lighter"
        >
          Read the full referral terms
        </Link>
      </div>
    </div>
  );
}
